### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by skurilyak** [Rawnly/splash-cli#12]
### Basic informations
- **splash-cli** version: `2.3.4`
- NodeJs version: `4.3.0`
- Your OS: **macOS Sierra, 10.12.3 (16D32)**

# ISSUE
When I run `$ splash` I get the following error:

```
false
✔ Connected!
✔ Making something awsome

/usr/local/lib/node_modules/splash-cli/libs/download.js:67
    log(`Shooted by: ${creator.fullname.cyan.bold} (${creator.username.yellow})`);
                                            ^

TypeError: Cannot read property 'bold' of undefined
    at infos (/usr/local/lib/node_modules/splash-cli/libs/download.js:67:45)
    at WriteStream.response.pipe.on (/usr/local/lib/node_modules/splash-cli/libs/download.js:120:7)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:515:14)
    at afterWrite (_stream_writable.js:389:3)
    at onwrite (_stream_writable.js:379:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fs.js:2137:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:747:5)
```

Please advise.

**Comment by Rawnly** [comment]
I'm sorry, but actually i don't have an able computer, @helloyou2012 has fixed it but right now i can't update the module... sorry for issue
