### ISSUE TITLE
cairo dependency?

### ISSUE THREAD

**Issue by AlecRust** [Rawnly/splash-cli#15]
### Basic informations
- **splash-cli** version: `2.3.9`
- NodeJs version: `v7.7.2`
- Your OS: **macOS 10.12.4**

# ISSUE
`npm i -g splash-cli` failed with the following error. `brew install cairo` was required first to complete the install successfully.

```shell
> canvas@1.2.11 install /Users/alec/.nvm/versions/node/v7.7.2/lib/node_modules/splash-cli/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/alec/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/alec/.nvm/versions/node/v7.7.2/bin/node" "/Users/alec/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alec/.nvm/versions/node/v7.7.2/lib/node_modules/splash-cli/node_modules/canvas
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
/Users/alec/.nvm/versions/node/v7.7.2/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alec/.npm/_logs/2017-04-08T22_28_16_030Z-debug.log
```

**Comment by Rawnly** [comment]
Cairo is not "ufficially" a dependecy... maybe some dependents package needs it. I'll investigate on this. It's never happened.
