### ISSUE TITLE
Error when running `node cli`

### ISSUE THREAD

**Issue by FredrikAugust** [Rawnly/splash-cli#5]
So, I cloned the repo, and the first thing it complains about is missing `"use strict";`, which I fixed in my clone, but after that it complains when running `node cli.js`/`node cli` and gives the following error:

```
/home/fredrik/Downloads/splash-cli/node_modules/chili-js/index.js:35
module.exports = String.prototype.capitalize = function(divider = ' ', joiner = divider) {
                                                                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/fredrik/Downloads/splash-cli/libs/variables.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10
```

**Comment by FredrikAugust** [comment]
I even tried installing `babel-cli` to force it to use ECMAscript 2015, but it gives the same error.

**Comment by Rawnly** [comment]
> So, I cloned the repo, and the first thing it complains about is missing "use strict";

I didn't include it because i use an external file (`libs/variables.js`) for variables, and it gives error while running. 

I'll check `chili-js`, thanks for report.
